// soft_lvds_ip.v

// Generated using ACDS version 25.1 1129

`timescale 1 ps / 1 ps
module soft_lvds_ip (
		input  wire        tx_inclock,   //   tx_inclock.tx_inclock
		input  wire        tx_syncclock, // tx_syncclock.tx_syncclock
		input  wire [39:0] tx_in,        //        tx_in.tx_in
		output wire [3:0]  tx_out        //       tx_out.tx_out
	);

	altera_soft_lvds_tx_ERzqh soft_lvds_ip_inst (
		.tx_inclock   (tx_inclock),   //   tx_inclock.tx_inclock
		.tx_syncclock (tx_syncclock), // tx_syncclock.tx_syncclock
		.tx_in        (tx_in),        //        tx_in.tx_in
		.tx_out       (tx_out),       //       tx_out.tx_out
		.tx_outclock  (),             //  (terminated)
		.tx_coreclock (),             //  (terminated)
		.tx_locked    ()              //  (terminated)
	);

endmodule
